version: '2'

services:
  lora-app-server:
    build:
      context:    lora-app-server
      dockerfile: Dockerfile
    ports:
      # application_server.external_api
      - 8081:8080
    volumes:
      - /home/pi/lorawan/lora-app-server_conf.toml:/etc/lora-app-server/lora-app-server.toml:ro
    depends_on:
      - postgres-appsrv
      - redis
      - mosquitto
      - loraserver
    logging:
      driver: journald
      options:
        mode: non-blocking
        max-buffer-size: 1m

  loraserver:
    build:
      context:    loraserver
      dockerfile: Dockerfile
    volumes:
      - /home/pi/lorawan/loraserver_conf.toml:/etc/loraserver/loraserver.toml:ro
    depends_on:
      - postgres
      - redis
      - mosquitto
    logging:
      driver: journald
      options:
        mode: non-blocking
        max-buffer-size: 1m

  postgres-appsrv:
    image: postgres:alpine
    volumes:
      - postgres-appsrv_data:/data
      - postgres-appsrv_sql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=loraserver_as
      - POSTGRES_USER=loraserver_as
      - POSTGRES_DB=loraserver_as
    logging:
      driver: journald
      options:
        mode: non-blocking
        max-buffer-size: 1m

  postgres:
    image: postgres:alpine
    volumes:
      - postgres_data:/data
      - postgres_sql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=loraserver
      - POSTGRES_USER=loraserver
      - POSTGRES_DB=loraserver
    logging:
      driver: journald
      options:
        mode: non-blocking
        max-buffer-size: 1m

  redis:
    build:
      context:    redis/3.2/alpine
      dockerfile: Dockerfile
    volumes:
      - redis_data:/data
    logging:
      driver: journald
      options:
        mode: non-blocking
        max-buffer-size: 1m

  mosquitto:
    build:
      context:    mosquitto
      dockerfile: Dockerfile
    ports:
      - "1883:1883"  # Note: your MQTT broker should use authentication in production environments
    logging:
      driver: journald
      options:
        mode: non-blocking
        max-buffer-size: 1m
  
  bridge:
    build:
      context:    gateway/lora-gateway-bridge
      dockerfile: Dockerfile
    volumes:
      - /home/pi/lorawan/lora-gateway-bridge_conf.toml:/etc/lora-gateway-bridge/lora-gateway-bridge.toml
    depends_on:
      - mosquitto
    logging:
      driver: journald
      options:
        mode: non-blocking
        max-buffer-size: 1m

  forwarder:
    build: 
      context:    gateway/rpi-ttn-gateway
      dockerfile: Dockerfile
    volumes:
      - forwarder_cgroups:/sys/fs/cgroup
    environment:
      PI_RESET_PIN: 7
      GATEWAY_EUI: "010203"
      ROUTER_ADDR: bridge
      GATEWAY_NAME: "forwarder"
    privileged: true
    depends_on:
      - bridge
    logging:
      driver: journald
      options:
        mode: non-blocking
        max-buffer-size: 1m

volumes:
  postgres_data:
  postgres-appsrv_data:
  postgres_sql_data:
  postgres-appsrv_sql_data:
  redis_data:
  forwarder_cgroups:
