FROM golang:1.10-alpine

ENV PROJECT_PATH=/go/src/github.com/brocaar/loraserver
ENV PATH=$PATH:$PROJECT_PATH/build
ENV CGO_ENABLED=0
ENV GO_EXTRA_BUILD_ARGS="-a -installsuffix cgo"
ENV GOOS=linux GOARCH=arm GOARM=7

RUN apk add --no-cache ca-certificates tzdata make git bash protobuf alpine-sdk ruby ruby-dev libffi-dev
RUN gem install --no-ri --no-rdoc fpm

RUN mkdir -p $PROJECT_PATH
COPY . $PROJECT_PATH
WORKDIR $PROJECT_PATH

RUN make requirements
