ARG TTN_IMAGE=ttn-armv7l:latest
FROM $TTN_IMAGE

COPY generated/router.yml /etc/ttn/router/ttn.yml
COPY generated/discovery.cert /etc/ttn/router/ca.cert

RUN cd /etc/ttn/router; \
ttn router gen-keypair --config ./ttn.yml && \
ttn router gen-cert --config ./ttn.yml

CMD ["router", "--config", "/etc/ttn/router/ttn.yml"]
