ARG TTN_IMAGE=ttn-armv7l:latest
FROM $TTN_IMAGE

COPY generated/handler.yml /etc/ttn/handler/ttn.yml
COPY generated/discovery.cert /etc/ttn/router/ca.cert

RUN cd /etc/ttn/handler; \
ttn handler gen-keypair --config ./ttn.yml && \
ttn handler gen-cert --config ./ttn.yml

CMD ["handler", "--config", "/etc/ttn/handler/ttn.yml"]
