id: agile-broker
description: "TTN Broker Server"
tls: true
key-dir: /etc/ttn/broker/
auth-servers:
  ttn-account-v2: "https://account.thethingsnetwork.org"

discovery-address: "discovery:1900"
auth-token: ${DISCOVERY_BROKER_ACCESS_TOKEN}

broker:
  server-address-announce: agile-broker
  networkserver-address: "networkserver:1903"
  networkserver-cert: /etc/ttn/broker/networkserver.cert
  networkserver-token: ${NETWORKSERVER_BROKER_ACCESS_TOKEN}
