id: agile-networkserver
description: "TTN Network Server"
tls: true
key-dir: /etc/ttn/networkserver/
discovery-address: "discovery:1900"
auth-servers:
  ttn-account-v2: "https://account.thethingsnetwork.org"

networkserver:
  server-address-announce: agile-networkserver
  redis-address: redis:6379
