git:
  short_hash: true

builds:
  - main: cmd/lora-app-server/main.go
    binary: lora-app-server
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

release:
  draft: true
